# Generated by Django 3.1.4 on 2020-12-28 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='compamy_name',
            new_name='company_name',
        ),
    ]
