# Generated by Django 3.1.4 on 2020-12-29 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_subscribers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribers',
            new_name='Subscriber',
        ),
    ]
